export default [
  {
    _id: "1",
    name: "God Of War: Ragnarok",
    image: "/images/GOW.jpg",
    description:
      "God of War Ragnarok is the next chapter in the story of Kratos and his growing son Atreus as they prepare for the titular cataclysm that threatens to be unleashed upon not just the Norse lands of Midgard, but all of the nine realms.",
    brand: "Sony",
    category: "Electronics",
    price: 69.99,
    countInStock: 10,
    rating: 5,
    numReviews: 12,
  },
  {
    _id: "2",
    name: "Detroit: Become Human ",
    image: "/images/human.jpg",
    description:
      "puts the destiny of both mankind and androids in your hands, taking you to a near future where machines have become more intelligent than humans",
    brand: "Sony",
    category: "Electronics",
    price: 59.99,
    countInStock: 7,
    rating: 4.8,
    numReviews: 8,
  },
  {
    _id: "3",
    name: "Assassin's Creed Mirage",
    image: "/images/mirage.jpg",
    description:
      "Experience the story of Basim, a cunning street thief seeking answers and justice as he navigates the bustling streets of 9th-century Baghdad, becoming a deadly Master Assassin, changing his fate in ways he never could have imagined.",
    brand: "Sony",
    category: "Electronics",
    price: 64.99,
    countInStock: 5,
    rating: 4.1,
    numReviews: 12,
  },
  {
    _id: "4",
    name: "Mortal Kombat 1",
    image: "/images/MK.jpg",
    description:
      "a powerless Shang Tsung attempts to make a living in Outworld as a con man until he is approached by a mysterious individual named Damashi, who reveals his potential to become a sorcerer and that unseen forces are working against him.",
    brand: "Sony",
    category: "Electronics",
    price: 69.99,
    countInStock: 11,
    rating: 5,
    numReviews: 12,
  },
  {
    _id: "5",
    name: "Modern Warfare 3",
    image: "/images/MW3.jpg",
    description:
      "multi-national special operations unit Task Force 141 tracking down Vladimir Makarov, a Russian ultranationalist and terrorist planning to trigger a third World War.",
    brand: "Sony",
    category: "Electronics",
    price: 59.99,
    countInStock: 7,
    rating: 3.8,
    numReviews: 10,
  },
  {
    _id: "6",
    name: "PS5 Controller Cosmic Red",
    image: "/images/controller.jpg",
    description:
      "The DualSense wireless controller for PS5 consoles offers immersive haptic feedback2, dynamic adaptive triggers2 and a built-in microphone, all integrated into an iconic design.",
    brand: "Sony",
    category: "Electronics",
    price: 74.99,
    countInStock: 0,
    rating: 4.5,
    numReviews: 12,
  },
];
